version: '3.3'

services:
 mongo:
  container_name: mongo
  image: mongo:6.0
  restart: on-failure:10
  volumes:
   - ./data:/data/db
  ports:
   - "27017:27017"
 postgres:
  container_name: my-postgres
  image: postgres:latest
  restart: always
  environment:
    POSTGRES_PASSWORD: abc@123
  volumes:
    - ./postgres-data:/data/db
  ports:
    - "5432:5432"