version: '3.9'
services:
  xyz:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
